### ISSUE TITLE
Issue with highlights

### ISSUE THREAD

**Issue by nfoong** [zxdawn/rM2PDF#2]
Hi, I got it working on a Ubuntu machine, but I've noticed that in the output pdfs under "noted_pdf", highlights are solid black, making it impossible to read the thing that it is highlighting. Is it possible to fix this?

There is also a slight mismatch in the placing of the highlights and pen strokes, but this is a minor issue. 

Thanks!

<img width="834" alt="screen shot 2018-03-02 at 12 43 05 am" src="https://user-images.githubusercontent.com/30332390/36877669-3561ef82-1db3-11e8-9491-d21d4a7f9fdc.png">

**Comment by florian-wagner** [comment]
Hi @nfoong,

I have mapped black to blue, grey to red and the highlighter to opaque yellow, which works great for annotating documents as you can see here: https://github.com/reHackable/maxio/files/1695105/remarkable-c.pdf

Therefore I have created the `-c` option for the exportNotebook script here: https://github.com/reHackable/maxio

But also with the rM2PDF script here, you can change the colors once it's using the highlighter: https://github.com/zxdawn/rM2PDF/blob/master/rM2svg.py#L131

**Comment by nfoong** [comment]
Hi @florian-wagner,

The rM2svg script on @zxdawn's github repository isn't the same as the one on maxio, so it doesn't support the `-c` option. But in any case, I have gotten an updated version of rM2svg off the maxio repository and i can confirm that colours do indeed work. (I also managed to get the script working on macOS this time)

The issue is with the opacity with polyline. Setting highlights as 0.2 doesn't seem to be registering, hence the highlights still remain fully opaque as though opacity=1. Any idea why this is the case?

Thanks!

<img width="860" alt="screen shot 2018-03-02 at 11 28 22 am" src="https://user-images.githubusercontent.com/30332390/36897102-1fe2497c-1e0d-11e8-98a4-b2f958c6fe6d.png">

**Comment by zxdawn** [comment]
What about the opacity of svg? Could you upload a example?

**Comment by zxdawn** [comment]
Hi @nfoong and @florian-wagner ,

I checked the highlight function and found that svg files are fine for highlight. But, after I converted svg to pdf by '[svg2pdf](https://github.com/deeplook/svglib)', the opacity of highlights in pdf is 1. So, how did @florian-wagner convert svg to pdf?

Thanks,
Xin

**Comment by florian-wagner** [comment]
Imagicks convert and rsvg-convert produced good results. I prefer the latter as it does not rasterize.

**Comment by zxdawn** [comment]
@florian-wagner Thank you for your help!
@nfoong You can check it again. I have updated rM2svg and rM2PDF.

**Comment by nfoong** [comment]
@zxdawn I just got round to testing it, and rsvg-convert works great!

You might want to tidy up rM2PDF.py:
1. Get rid of line 25: `if prefix == '483e3894-f057-498a-a9cd-bb16e10255ac':`
2. Notebooks don't convert properly because you haven't updated them to use rsvg-convert. Get rid of `temporary*.pdf` and replace with `note.pdf` in the last 2 lines and everything should work fine

Thanks again for your help, @florian-wagner too!

**Comment by zxdawn** [comment]
@nfoong OK, fix it.
